apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-4b-pvc
  namespace: kubeai
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem